name: Build and make binaries

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Set up project
      - uses:
          actions/checkout@v2
      - uses:
          actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i

      - name: Build project
      - run: npm run build

      - name: Make binaries
      - run: npm run package
      - uses:
          actions/upload-artifact@v2
        with:
          name: devops-toolbox-agent
          path: bin
